#!/bin/sh

### BEGIN INIT INFO
# Provides:          networking
# Required-Start:    mountkernfs $local_fs
# Required-Stop:     $local_fs
# Should-Start:      ifupdown
# Should-Stop:       ifupdown
# Default-Start:     S
# Default-Stop:      0 6 
# Short-Description: Raise network interfaces.
### END INIT INFO

start() {
	if [ -f /etc/network/interfaces ]; then
		echo "" > /var/run/ifstate
		ifup -a
	fi
	return
}

stop() {
	if [ -f /etc/network/interfaces ]; then
		ifdown -a
	fi
	return
}

case $1 in
	 "start") start ;;
	 "stop") stop ;;
	 "restart") stop && start ;;
	 *)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
