#!/bin/sh

### BEGIN INIT INFO
# Provides:          umountall
# Required-Start:    
# Required-Stop:     
# Should-Start:      
# Should-Stop:       halt reboot kexec
# Default-Start:     
# Default-Stop:      0 6 
# Short-Description: Unmount all file system.
### END INIT INFO

# Unmount according to fstab
echo "Unmounting filesystem..."
sync; sync; sync
umount -a -f -r 2> /dev/null || true
sync; sync; sync
