diff -Naur gnutls26-2.8.6-1.org//lib/po/Makefile.in.in gnutls26-2.8.6-1/lib/po/Makefile.in.in
--- gnutls26-2.8.6-1.org//lib/po/Makefile.in.in	2012-05-25 08:33:19.000000000 +0000
+++ gnutls26-2.8.6-1/lib/po/Makefile.in.in	2012-05-25 08:34:33.000000000 +0000
@@ -9,7 +9,7 @@
 # General Public License and is *not* in the public domain.
 #
 # Origin: gettext-0.17
-GETTEXT_MACRO_VERSION = 0.17
+GETTEXT_MACRO_VERSION = 0.18
 
 PACKAGE = @PACKAGE@
 VERSION = @VERSION@
diff -Naur gnutls26-2.8.6-1.org//lib/gl/m4/po.m4 gnutls26-2.8.6-1/lib/gl/m4/po.m4
--- gnutls26-2.8.6-1.org//lib/gl/m4/po.m4	2012-05-25 08:33:19.000000000 +0000
+++ gnutls26-2.8.6-1/lib/gl/m4/po.m4	2012-05-25 08:35:27.000000000 +0000
@@ -29,7 +29,7 @@
 
   dnl Release version of the gettext macros. This is used to ensure that
   dnl the gettext macros and po/Makefile.in.in are in sync.
-  AC_SUBST([GETTEXT_MACRO_VERSION], [0.17])
+  AC_SUBST([GETTEXT_MACRO_VERSION], [0.18])
 
   dnl Perform the following tests also if --disable-nls has been given,
   dnl because they are needed for "make dist" to work.
diff -Naur gnutls26-2.8.6-1.org//lib/m4/po.m4 gnutls26-2.8.6-1/lib/m4/po.m4
--- gnutls26-2.8.6-1.org//lib/m4/po.m4	2012-05-25 08:33:18.000000000 +0000
+++ gnutls26-2.8.6-1/lib/m4/po.m4	2012-05-25 08:36:01.000000000 +0000
@@ -29,7 +29,7 @@
 
   dnl Release version of the gettext macros. This is used to ensure that
   dnl the gettext macros and po/Makefile.in.in are in sync.
-  AC_SUBST([GETTEXT_MACRO_VERSION], [0.17])
+  AC_SUBST([GETTEXT_MACRO_VERSION], [0.18])
 
   dnl Perform the following tests also if --disable-nls has been given,
   dnl because they are needed for "make dist" to work.
